### ISSUE TITLE
7.6.4 - release note tracking

### ISSUE THREAD

**Issue by cmrn-rhi** [cidgoh/GRDI_AMR_One_Health#23]
## Template Fixes:
- Removed unwanted spaces trialing ontology IDs of the `host (food production name)` field terms: "**Nursing pig [FOODON:00004297 ]**" and "**Tom (Gobbler) [FOODON:00004304 ]**".

## Specification Changes:

| Field | Change |
| --- | --- |
| `food_product` | New picklist IDs and definitions. |
| `host (food production name)` | Removed unwanted blank spaces. |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = 7 = N/A
y = 6 = New IDs
z = 4 = New definitions, minor fixes

New Term SOP N/A unless indicated.

**Comment by cmrn-rhi** [comment]
## ID/Definition Updates

### `food_product`
| term | new ID | definition |
| --- | --- | --- |
| Compound feed premix | FOODON:00004323 | A formula mixture of micronutrients that is used as a component in compound feed. |
| Compound feed premix (medicated) | FOODON:00004324 | A compound feed premix in which medicinal substance has been added. |
| Animal feed ingredient | FOODON:00004322 | An ingredient that is used in the preparation of animal feed. |

**Comment by cmrn-rhi** [comment]
**To-Do** @cmrn-rhi 
- [ ] Field: AMR_laboratory_typing_platform
  - remove phenotype picklist options
- [ ] Tab: AMR Phenotypic Test Information
   - [ ] remove columns J to O and T to V
   - [ ] add unit column to all the antibiotic fields
   - [ ] reorder antibiotic fields so they are measurement > units > sign
- [ ] new fields (reference guide)
- [ ] new vocabulary (reference guide)

**Comment by cmrn-rhi** [comment]
- [ ] increase merge row count from 1500 to at least 2000, if not more (depends on slow down).

**Comment by cmrn-rhi** [comment]
Note: 7.5.3 was only released as a DataHarmonizer (DH) Template. 7.6.4 will be released as the excel template and a DH pathogen genomics template.

**Comment by cmrn-rhi** [comment]
[ ] update README to direct people to the DH template option.

**Comment by cmrn-rhi** [comment]
- [ ] Could make it so `0`s don't appear in the absence of values (which create ambiguity around fields with numerical inputs. If done, do after everything else so it's easy to revert.

`=IF(condition, if true, if false)`

`=IF(<formula>=0, "", <formula>)`

`=IF(INDEX('Strain and Isolate Information'!D:D, MATCH('Merged Sheet'!C3,'Strain and Isolate Information'!E:E, 0))=0,"",INDEX('Strain and Isolate Information'!D:D, MATCH('Merged Sheet'!C3,'Strain and Isolate Information'!E:E, 0)))`

Would make editing the merge sheet more tedious.

**Comment by cmrn-rhi** [comment]
- [ ]  add antibiotic unit and sign picklists as outlines in DH template

**Comment by cmrn-rhi** [comment]
- [ ] Add "date precision" fields where applicable (based on discussions in GRDI workgroup meeting 2023-05-16)

**Comment by cmrn-rhi** [comment]
**Fields/Vocab Updates:**
sample_collected_by
presampling_activity
geo_loc_name (state/province/region)
sample_collection_date_precision **NEW**
environmental_site
available_data_types
weather_type
animal_or_plant_population
environmental_material
body_product
anatomical_part
anatomical_region **NEW**
food_product
food_product_properties
production_stream **NEW**
collection_device
collection_method
food_packaging
host (common name)
host (scientific name)
host (food production name)
host_age_bin **NEW**
isolated_by
organism
sequencing_instrument
antimicrobial_agent_name
AMR_laboratory_typing_platform
sediment_depth **NEW**
water_temperature **NEW**
