### ISSUE TITLE
8.8.7 - release note tracking

### ISSUE THREAD

**Issue by cmrn-rhi** [cidgoh/GRDI_AMR_One_Health#38]
## Template Fixes:
- Additional, unwanted spaces trimmed from `host (common name)` picklist terms (e.g. between term label and term ID).

## Specification Changes:

| Field | Change |
| --- | --- |
| `presampling_activity` | NEW PICKLIST IDs: Certified humane animal husbandry practices [GENEPIO:0100894], Conventional farming practices [GENEPIO:0100895] |
| `specimen_processing` | NEW PICKLIST Definition: Samples pooled [OBI:0600016] |
| `geo_loc_name (state/province/region)` | NEW PICKLIST IDs: Atlantic region (Canada) [wikidata:Q246972], Central region (Canada) [wikidata:Q1048064], Northern region (Canada) [wikidata:Q764146], Pacific region (Canada) [wikidata:Q122953299], Prairie region (Canada) [wikidata:Q1364746] |
| `environmental_site` | NEW PICKLIST IDs: Pigsty [ENVO:03501413], Dairy farm [ENVO:03501416] |
| `animal_or_plant_population` | NEW PICKLIST IDs/Definitions: Wildlife [FOODON:00004503], Wild bird [FOODON:00004505]; NEW PICKLIST ID: Seabird [FOODON:00004504] |
| `environmental_material` | NEW PICKLIST IDs/Definitions: Dead haul trailer [GENEPIO:0100896], Live haul trailer [GENEPIO:0100897]; NEW PICKLIST IDs: Bulk tank [ENVO:03501379], Nest [ENVO:03501432]; NEW PICKLIST LABEL: Contaminated water [ENVO:00002186] |
| `body_product` | NEW PICKLIST IDs: Digestive tract substance [GENEPIO:0100898], Caecal content [GENEPIO:0100899], Intestinal content [GENEPIO:0100900], Stomach content [GENEPIO:0100901]; NEW DEFINITIONS: Fecal composite, Feces (fresh), Feces (environmental) |
| `anatomical_part` | NEW PICKLIST ID: Fish vent [GENEPIO:0100902] |
| `food_product` | NEW PICKLIST ID: Compound feed premix [FOODON:00004323], Compound feed premix (medicated) [FOODON:00004324], Animal feed ingredient [FOODON:00004322], Potato [FOODON:03315354] |
| `food_product_properties` | NEW PICKLIST IDs: Meat (with bone) [FOODON:02010116], Meat (with skin) [FOODON:02010111] |
| `food_product_production_stream` | NEW FIELD changes: `production_stream` label changed to `food_product_production_stream`; slight adjustments to definition; updated example; REMOVED PICKLIST VALUES: Food animal production stream [FOODON:03000450], Food product production stream [FOODON:03000457]; NEW PICKLIST IDs: Beef cattle production stream [FOODON:03000452], Broiler chicken production stream [FOODON:03000455], Dairy cattle production stream [FOODON:03000453], Layer chicken production stream [FOODON:03000456], Egg production stream [FOODON:03000458], Meat production stream [FOODON:03000460], Milk production stream [FOODON:03000459], NEW PICKLIST LABEL & ID: Veal meat production stream [FOODON:03000461],
| `host (common name)` | NEW PICKLIST ID: Seabird [FOODON:00004504] |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = 8 = Field relabeled
y = 8 = New value/picklist IDs
z = 7 = New definitions

New Term SOP update.

## Template To-Dos
- [x] Update IDs
  - [x] Excel Template
  - [x] DH Template
- [x] Update `production_stream` -> `food_product_production_stream` field label
  - [x] Excel Template
  - [x] DH Template

**Comment by cmrn-rhi** [comment]
## Update issue request protocol
_Approved in workgroup meeting 2023-10-17._
- [ ] Convert issue templates to issue forms
  - [x] Specification - Change Field Request
  - [ ] Specification - Change Term Request
  - [ ] Specification - New Term Request (Bulk)
  - [ ] Specification - New Term Request
- [ ] Update protocol document images and text to accommodate changes.
