### ISSUE TITLE
8.9.8 - release note tracking

### ISSUE THREAD

**Issue by cbarcl01** [cidgoh/GRDI_AMR_One_Health#56]
## Specification Changes:

| Field | Change |
| --- | --- |
| `organism` | New picklist values as requested in issues |
| `collection_method` | Added IDs to picklist values |
| `collection_device` | Added IDs and updated definition to picklist values |
| `specimen_processing` | Added IDs to picklist values |
| `environmental_site` | Added IDs to picklist values |
| `environmental_material` | Added IDs and updated definition to picklist values |
| `body_product` | Added IDs and updated definition to picklist values |
| `anatomical_part` | Added IDs to picklist values |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = # = no changes
y = 9 = new picklist values
z = 8 = definitions for new picklist values

New Term SOP N/A unless indicated.

## Template To-Dos
- [x] Update picklist value labels/IDs/descriptions
  - [x] Excel Template
  - [x] DataHarmonizer Template ([GRDI-enums](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=839182863&range=A1))
- [ ] Update field labels/IDs/descriptions
  - [ ] Excel Template
  - [ ] DataHarmonizer Template ([GRDI-slots](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=134572699&range=A1))

**Comment by cbarcl01** [comment]
Organism | ID
-- | --
Aeromonas rivipollensis | NCBITaxon:948519
Aeromonas salmonicida | NCBITaxon:645
Citrobacter gillenii | NCBITaxon:67828
Clostridium sporogenes | NCBITaxon:1509
Exiguobacterium | NCBITaxon:33986
Exiguobacterium oxidotolerans | NCBITaxon:223958
Exiguobacterium sp. | NCBITaxon:44751
Kluyvera | NCBITaxon:579
Kluyvera intermedia | NCBITaxon:61648
Photobacterium | NCBITaxon:657
Photobacterium sp. | NCBITaxon:660
Pseudoalteromonas | NCBITaxon:53246
Pseudoalteromonas tetraodonis | NCBITaxon:43659
Psychrobacter | NCBITaxon:497
Psychrobacter faecalis | NCBITaxon:180588
Psychrobacter sp. | NCBITaxon:56811
Shewanella | NCBITaxon:22
Shewanella pealeana | NCBITaxon:70864
Shewanella putrefaciens | NCBITaxon:24
Shewanella sp. | NCBITaxon:50422

**Comment by cbarcl01** [comment]
collection_method | ID
-- | --
Water filtration | GENEPIO:0100931
Scooping | GENEPIO:0100932
Sediment collection | GENEPIO:0100933
Soil coring | GENEPIO:0100934

**Comment by cbarcl01** [comment]
collection_device | ID | Definition 
-- | -- | --
Box corer | GENEPIO:0100928 | A specimen collection device that is used to collect soft sediments in lakes or oceans.
PONAR grab sampler | GENEPIO:0100929 | A specimen collection device that is used to collect sediment samples from hard bottoms. 
Soil sample probe | GENEPIO:0100930 | A specimen collection device that is used to collect a soil sample from the ground.

**Comment by cbarcl01** [comment]
specimen_processing | ID
-- | --
Isolated from single source | GENEPIO:0100926

**Comment by cbarcl01** [comment]
environmental_site | ID
-- | --
Breeding ground | ENVO:03501441
Beef farm | ENVO:03501443
Beef cattle feedlot | ENVO:03501444

**Comment by cbarcl01** [comment]
environmental_material | ID | Definition
-- | -- | --
Fecal slurry | ENVO:03501436 |
Influent | ENVO:03501442 | Contaminated or untreated water which is flowing into a wastewater treatment plant for processing.

**Comment by cbarcl01** [comment]
body_product | ID | Definition
-- | -- | --
Digestive tract substance | GENEPIO:0100898 | Undigested food material, microbiota, and other materials found in the digestive tract.
Caecal content | GENEPIO:0100899 | Undigested food material, microbiota, and other materials found in the cecum
Intestinal content | GENEPIO:0100900 | Undigested food material, microbiota, and other materials found in the intestine
Stomach content | GENEPIO:0100901 | Undigested food material, microbiota, and other materials found in the stomach
Fecal composite | GENEPIO:0004512 |
Feces (fresh) | GENEPIO:0004513 |
Feces (environmental) | GENEPIO:0004514 |

**Comment by cbarcl01** [comment]
anatomical_part | ID 
-- | --
Mantle (bird) | GENEPIO:0100927

**Comment by cbarcl01** [comment]
Newest release [v.8.9.8](https://github.com/cidgoh/GRDI_AMR_One_Health/releases/tag/v8.9.8)
