### ISSUE TITLE
12.2.2 - release note tracking

### ISSUE THREAD

**Issue by cbarcl01** [cidgoh/GRDI_AMR_One_Health#88]
## Specification Changes:

| Field | Change |
| --- | --- |
| `animal_source_of_food` | New picklist IDs |
| `food_product` | New picklist IDs, change picklist IDs, new definitions |
| `label claim` | New field |
| `taxonomic_identification_process` | New picklist IDs |
| `environmental_material_constituent` | New field |
| `collection_device` | Change picklist ID |

### Version Tracking:
Excel Template, Reference Guides, Curation SOP

x = 12 = New field 
y = 2 = New IDs
z = 1 = <def/format/example changes>

New Term SOP N/A unless indicated.

## Template To-Dos
- [ ] Update picklist value labels/IDs/descriptions
  - [ ] Excel Template
  - [ ] DataHarmonizer Template ([GRDI-enums](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=839182863&range=A1))
- [ ] Update field labels/IDs/descriptions
  - [ ] Excel Template
  - [ ] DataHarmonizer Template ([GRDI-slots](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=134572699&range=A1))

**Comment by cbarcl01** [comment]
New terms requested by Sandeep Tamber.

From conversation with Emma: 

Can we add mussel and oyster to food product list under shellfish? 

- Mussel [FOODON:03411223]
- Oyster [FOODON:03411224]

Also under produce:

- Karela (Bitter melon) [FOODON:00004367] 

Under tax id process?

- Matrix Assisted Laser Desorption Ionization imaging mass spectrometry assay (MALDI) [OBI:0003099]

**Comment by cbarcl01** [comment]
From conversation with Emma:

We might need to separate out label claims from food product properties. There is a need for requesting things like antibiotic-free in addition to organic. Distinguishong between them will also be more in-line with the US One health Biosample.

**Comment by cbarcl01** [comment]
Need to capture what an environmental material is composed of (for example a plastic pipe vs a lead pipe etc). Suggestion `environmental material constituent`

**Comment by cbarcl01** [comment]
NTR #87

**Comment by cbarcl01** [comment]
NTR #86

**Comment by cbarcl01** [comment]
NTR #85

**Comment by cbarcl01** [comment]
Update term for 'collection tube'. Currently references an uberon term which is not appropriate for use so need to usenew term  'sample collection tube' GENEPIO:0101196

**Comment by cbarcl01** [comment]
Resolved changes to missing FOODON IDs. Some IDs were included in GRDI but had not yet been surfaced in EBI OLS. This was mostly due to a modelling change in food characteristics that had happened in FOODON.

**Comment by cbarcl01** [comment]
Update Fields experimental_specimen_role_type and specimen_processing to ensure IDs are consistent with processing vs the role.
 
 From Gabriel: the ids are slightly different technical replicates for example has the same number, but the prefix is different: one with OBI and another one with EFO, is that correct?

From Charlie: Biological replicate, based on the definition the EFO term is a better fit for 'experimental_specimen_role_type'. It looks like the biological and technical replicate terms under 'specimen_processing' have been left there as a legacy of earlier templates, when there was no other place to capture this info. In other specifications we have changed this to 'Biological replicate processing' and 'Technical replicate processing', to better reflect the field.

**Comment by cbarcl01** [comment]
Preparing release for 10/07/2024

**Comment by cbarcl01** [comment]
PR #90
